version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=job
      - POSTGRES_DB=management-job
